services:
  # Frontend - Vue.js application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    ports:
      - "2025:80"
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  portfolio-network:
    driver: bridge

volumes:
  # Optional: For persistent data if needed
  portfolio-data:
    driver: local
