services:
  # Frontend - Vue.js application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: portfolio-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend - Express API server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.server
    container_name: portfolio-backend
    ports:
      - "5174:5174"
    environment:
      - NODE_ENV=production
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-465}
      - SMTP_SECURE=${SMTP_SECURE:-true}
    env_file:
      - .env
    networks:
      - portfolio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5174/api/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  portfolio-network:
    driver: bridge

volumes:
  # Optional: For persistent data if needed
  portfolio-data:
    driver: local
